### ISSUE TITLE
Problem with displaying pseudo-elements

### ISSUE THREAD

**Issue by OlegZavrazhin** [houd1ni/fela-vue#17]
```
.socials {
  position relative

  &:before {
    content ''
    position absolute
  }

  &:after {
    content ''
    position absolute
  }
}
```

**Describe the bug**
Pseudo-elements don't display after sources build (minification)

**To Reproduce**
1. Computed style()
2. Add a "selector" with pseudo-elements
3. See the result
4. Pseudo-elements don't display

**Expected behavior**
Pseudo-elements display

**Screenshots**

**Desktop (please complete the following information):**
everywhere

**Smartphone (please complete the following information):**
everywhere

**Additional context**
I'll create PR with additional tests later

**Comment by houd1ni** [comment]
Hello, Oleg! Thank you for using the lib, the investigation and the new test case!

It's not obvious that classnames aren't real selectors, but only anchors between templates (this.f()) and style() property. Definitely could be better if changed to support those.

**Comment by houd1ni** [comment]
Note:
```
.socials:before {
    content ''
    position absolute
  }
```
should be translated into
```
.socials {
  &:before {
    content ''
    position absolute
  }
```

**Comment by houd1ni** [comment]
Done.
