### ISSUE TITLE
Dependabot updates

### ISSUE THREAD

**Issue by olegZavrazhinDecathlon** [houd1ni/fela-vue#40]
**Upgrade packages versions**
All info in "Pull requests" tab.

**Check for security alarms**

**Comment by houd1ni** [comment]
Hi, it's been a bit cumbersome, especially this https://github.com/houd1ni/fela-vue/issues/43 slipped out.
For now the lib itself works, although before tests are fixed I still have published it as beta release: `npm i -S fela-vue@2.6.0beta.46` or change version manually in package.json then run `npm i`.
As a bonus, `npm audit` should get rid of the bloody lines 😈

**Comment by houd1ni** [comment]
Try 2.6.0 release. Should be OK.

**Comment by houd1ni** [comment]
@olegZavrazhinDecathlon 2.6.0 should be updated. All dependabot PRs are done.
